from data_generation.plus_tab_gen import MonophonicTablatureEstimation
from data_generation.plus_audio_gen import AudioOverlay
from utils.misc import VIS_PATH

# First all guitar sources must be preprocessed. 
# You may run the guitar source preprocessing and audio generation separately if desired.
plus_loader = MonophonicTablatureEstimation()
file_annotations = plus_loader.load_plus(num_sources=None)
print('Results from MTE:')
print(len(plus_loader.warnings), 
      plus_loader.total_events_to_record,
      plus_loader.events_recorded)
text_file = open(VIS_PATH + '/Warnings_TabGen.txt', 'w')
text_file.write(str(plus_loader.warnings))

# The code below is to create audio for PLUS.
# It requires file_annotations first which is generated by the section above.
audio_overlayer = AudioOverlay(sr=44100, fade_alpha=0.1, cut_off_buffer=0.1,)
audio_overlayer.gen_plus('DadaGP', file_annotations,)
text_file = open(VIS_PATH + '/Warnings_AudioGen.txt', 'w')
text_file.write(str(audio_overlayer.warnings))
print(len(audio_overlayer.warnings))